name: example
description: "an application by normidar."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6

  image: ^4.1.7

  image_gen:
    path: ..

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  
  build_runner: ^2.4.6
  build_test: ^2.2.0





flutter:

  uses-material-design: true




