targets:
  $default:
    builders:
      source_gen|combining_builder: # Fix: Both source_gen:combining_builder and image_gen may output lib/image_gen.g.dart. Potential outputs must be unique across all builders.
        options:
          build_extensions:
            '^lib/{{}}.dart': 'lib/generated/{{}}.g.dart'
      auto_exporter:
        options:
          default_export_all: true
          project_name: image_gen


builders:
  image_gen:
    import: "package:image_gen/image_gen.dart"
    builder_factories: ["codeIconBuilder"]
    build_extensions: {".dart": [".png"]}
    build_to: source
    auto_apply: root_package