name: riverpod_helper
description: "A helpful tool for riverpod developer."
version: 0.0.2
homepage: https://github.com/normidar-group/normidar_dart_series/tree/main/apps/riverpod_helper

environment:
  sdk: '>=3.3.2 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.3
  auto_exporter_annotation: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  auto_exporter: ^3.3.0
  build_runner: ^2.4.6
  build_test: ^2.2.0

flutter:


