name: fm_firestore
description: "A package for firebase firestore"
version: 0.0.1
homepage: https://github.com/normidar-group/normidar_dart_series/tree/main/apps/firebase_manager

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  auto_exporter_annotation: ^1.0.1
  flutter:
    sdk: flutter
  cloud_firestore: ^4.4.5
  cloud_firestore_platform_interface: ^6.0.7
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  auto_exporter: ^3.3.1
  build_runner: ^2.4.11
  build_test: ^2.2.2


flutter:


