targets:
  $default:
    builders:
      auto_exporter:
        options:
          default_export_all: false # default export all files, if false only export @AutoExport() files, default is true.
          project_name: fm_storage