name: fm_storage
description: "an application by normidar."
version: 0.0.1
homepage: https://github.com/normidar-group/normidar_dart_series/tree/main/apps/firebase_manager

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  auto_exporter_annotation: ^1.0.1
  flutter:
    sdk: flutter

  crypto: ^3.0.2
  path_provider: ^2.0.13
  firebase_storage: ^11.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  auto_exporter: ^3.1.2
  build_runner: ^2.4.10
  build_test: ^2.2.2


flutter:


