name: ios_native_sensors
description: Flutter iOS plugin for accessing accelerometer, gyroscope, and magnetometer sensors, etc.
version: 0.0.2
homepage: https://github.com/normidar-group/normidar_dart_series/tree/main/apps/ios_native_sensors

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: FPPSensorsPlusPlugin

dependencies:
  flutter:
    sdk: flutter

  logging: ^1.2.0
  meta: ^1.8.0
  plugin_platform_interface: ^2.1.4

dev_dependencies:
  test: ^1.22.0
  flutter_test:
    sdk: flutter
  flutter_lints: ">=2.0.1 <4.0.0"

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"
