name: sensors_plus_example
description: Demonstrates how to use the sensors plugin.

dependencies:
  flutter:
    sdk: flutter
  ios_native_sensors: 
    path: ../

dev_dependencies:
  flutter_driver:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.19.0'
